### ISSUE TITLE
脚本的docker源是不是有问题 

### ISSUE THREAD

**Issue by java666888** [wukongdaily/OrangePiShell#13]
我发现 使用脚本 第五个功能 安装 小雅tvbox的时候 会出现一直无法下载docker镜像的问题 一直提示链接超时 无法从docker hub 下载镜像

**Comment by wukongdaily** [comment]
脚本中默认加入了1panel官方推荐的一些镜像源 本来以前是加速用的，结果现在各大镜像站也纷纷下架。
在1panel面板里 可再次设置一下docker 可用的代理源或者干脆删除所有镜像源。能挂梯就挂梯吧

**Comment by wukongdaily** [comment]
具体设置位置相见这里的截图 https://1panel.cn/docs/user_manual/containers/setting
![1Panel 2024-06-30 17-18-07](https://github.com/wukongdaily/OrangePiShell/assets/143675923/c853d4f8-9e22-4823-9d2c-23b650891294)

然后我这边调整了脚本。将加速地址修改为1panel官方推荐地址 https://docker.1panel.live
相关commit https://github.com/wukongdaily/OrangePiShell/commit/7c5a242bb547e1071bb87b2294adbfdc02047adb

**Comment by java666888** [comment]
OK 谢谢大佬
