### ISSUE TITLE
我这次重装发现， pi.sh 貌似有问题，

### ISSUE THREAD

**Issue by yangtao6519** [wukongdaily/OrangePiShell#16]
重装小雅tvbox, 发现貌似不能成功。尽管下载你Googledriver里面的镜像, 用1 panel 上传到 orangepi, /mnt.  也不行。
然后试一试重装小雅alist， 同样的问题。请看看？？？
<img width="450" alt="for wukong" src="https://github.com/wukongdaily/OrangePiShell/assets/16550448/62cdaf20-7bd0-4990-8419-0eaeb71e4dd2">

,

**Comment by wukongdaily** [comment]
建议试试这个1panel的加速地址。 `https://docker.1panel.live`
![1Panel 2024-06-30 17-18-07](https://github.com/wukongdaily/OrangePiShell/assets/143675923/12ad40ec-8e0b-436b-99a7-8c97c0983245)

**Comment by yangtao6519** [comment]
成功中，发现你也改了脚本？

**Comment by wukongdaily** [comment]
是的 改了脚本。
