### ISSUE TITLE
istoreOS 安装iPanle出错 Failed to get Docker root directory.

### ISSUE THREAD

**Issue by Zer0xPoint** [wukongdaily/OrangePiShell#17]
————————————————————————————————————————————————————

    ***********  DIY docker轻服务器  ***************
    环境:OpenWrt/iStoreOS
    脚本作用:快速部署一个省电无感的小透明轻服务器
            --- Made by wukong with YOU ---
    https://github.com/wukongdaily/OrangePiShell
 ————————————————————————————————————————————————————

 1. 安装小雅tvbox
 2. 安装盒子助手docker版
 3. 安装AList docker版
 4. 安装1panel(iStoreOS版)
 5. 安装特斯拉伴侣TeslaMate
 6. 安装docker-compose
 7. 安装小雅全家桶Emby|Jellyfin
 8. 安装1panel面板通用版
 U. 更新脚本

 Q. 退出本程序

请选择一个选项: 4
[INFO] 请务必确保您使用的是iStoreOS系统 回车或输入y来确定
[NOTICE] 并且停止正在运行的istorepanel容器(y|n)
y
[INFO] 先确保安装了iStore增强
Try mirror server https://repo.istoreos.com/repo
Package app-meta-istoreenhance (0.1.3-2) installed in root is up to date.
[INFO] 正在安装1panel的iStoreOS版本...
Removing package app-meta-istorepanel from root...
luci-i18n-istorepanel-zh-cn was autoinstalled and is now orphaned, removing.
Removing package luci-i18n-istorepanel-zh-cn from root...
luci-app-istorepanel was autoinstalled and is now orphaned, removing.
Removing package luci-app-istorepanel from root...
Not deleting modified conffile /etc/config/istorepanel.
zoneinfo-asia was autoinstalled and is now orphaned, removing.
Removing package zoneinfo-asia from root...
Collected errors:
 * file_sha256sum_alloc: Failed to open file /etc/config/istorepanel: No such file or directory.
Try mirror server https://repo.istoreos.com/repo
Installing app-meta-istorepanel (1.0.2-20240628) to root...
Downloading https://repo.istoreos.com/repo/all/meta/app-meta-istorepanel_1.0.2-20240628_all.ipk
Collected errors:
 * opkg_download: Failed to download https://repo.istoreos.com/repo/all/meta/app-meta-istorepanel_1.0.2-20240628_all.ipk, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_install_pkg: Failed to download app-meta-istorepanel. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package app-meta-istorepanel.
Try origin server https://istore.linkease.com/repo
Installing app-meta-istorepanel (1.0.2-20240628) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-istorepanel_1.0.2-20240628_all.ipk
Installing zoneinfo-asia (2023c-1) to root...
Downloading http://mirrors.pku.edu.cn/immortalwrt/releases/21.02.1/packages/aarch64_cortex-a53/packages/zoneinfo-asia_2023c-1_aarch64_cortex-a53.ipk
Installing luci-app-istorepanel (1.0.2-20231208) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-app-istorepanel_1.0.2-20231208_all.ipk
Installing luci-i18n-istorepanel-zh-cn (unknown) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-i18n-istorepanel-zh-cn_unknown_all.ipk
Configuring zoneinfo-asia.
Configuring luci-app-istorepanel.
Configuring luci-i18n-istorepanel-zh-cn.
Configuring app-meta-istorepanel.
[INFO] 正在安装istore版1panel...
Failed to get Docker root directory.

**Comment by wukongdaily** [comment]
应该就是你那边当时网络不佳 。没什么别的毛病了。多试几次就好了。检查一下 是不是你的节点不佳 先关闭
