### ISSUE TITLE
Error 22 when install FileBrowser

### ISSUE THREAD

**Issue by johnsfchan** [wukongdaily/OrangePiShell#19]
————————————————————————————————————————————————————

    ***********  DIY docker轻服务器  ***************
    环境: (Ubuntu/Debian/synology etc)
    脚本作用:快速部署一个省电无感的小透明轻服务器
            --- Made by wukong with YOU ---
    https://github.com/wukongdaily/OrangePiShell
 ————————————————————————————————————————————————————
请选择操作：
1. 更新系统软件包
2. 安装docker
3. 安装并启动文件管理器FileBrowser
4. 设置文件管理器开机自启动

Hi Wukong, I received the following message when using option 3:

请输入选项的序号(输入q退出): 3
[INFO] Downloading File Browser for linux/armv7...
https://cafe.cpolar.cn/wkdaily/filebrowser/raw/branch/main/linux-armv7-filebrowser.tar.gz
curl: (22) The requested URL returned error: 404
Aborted, error 22 in command: ${net_getter} "$filemanager_url" > "$PREFIX/tmp/$filemanager_file"
按任意键继续...

Please kindly assist.

**Comment by wukongdaily** [comment]
不好意思了 我没有上传32位arm的版本。。目前已经补充。

**Comment by wukongdaily** [comment]
https://cafe.cpolar.cn/wkdaily/filebrowser/raw/branch/main/linux-armv7-filebrowser.tar.gz

已补全资源文件。
