### ISSUE TITLE
文件管理器下载失败

### ISSUE THREAD

**Issue by ctr54188** [wukongdaily/OrangePiShell#2]
拼接的下载地址不对，没有中间的版本号，导致下载403
https://github.com/filebrowser/filebrowser/releases/download//linux-arm64-filebrowser.tar.gz

**Comment by ctr54188** [comment]
https://api.github.com/repos/filebrowser/filebrowser/releases/latest
这个接口有时返回错误

**Comment by wukongdaily** [comment]
收到，我大概了解了。可能这个api接口请求次数是有限制的。我调整一下方法吧。

**Comment by wukongdaily** [comment]
https://github.com/wukongdaily/OrangePiShell/commit/d3ae69d102efde3ce6b7ca9e06feafc0176f0ab7
