### ISSUE TITLE
你好，openssl连接这个连接有问题

### ISSUE THREAD

**Issue by dudu502** [wukongdaily/OrangePiShell#3]
orangepi@orangepizero3:~$ wget -O pi.sh https://mirror.ghproxy.com/https://raw.githubusercontent.com/wukongdaily/OrangePiShell/master/zero3/pi.sh && chmod +x pi.sh     ./pi.sh proxyent.com/wukongdaily/OrangePiShell/master/zero3/pi.sh && chmod +x pi                                                                                        --2024-04-27 11:31:38--  https://mirror.ghproxy.com/https://raw.githubusercontent.com/wukongdaily/OrangePiShell/master/zero3/pi.sh
Resolving mirror.ghproxy.com (mirror.ghproxy.com)... 132.145.248.22
Connecting to mirror.ghproxy.com (mirror.ghproxy.com)|132.145.248.22|:443... connected.
OpenSSL: error:0A00010B:SSL routines::wrong version number
Unable to establish SSL connection.

**Comment by wukongdaily** [comment]
orangepi zero3 首次使用先确保时间时区是否正确。如果不正确可以设置一下时区。查询命令如下
orangepi@orangepizero3:~$ `sudo timedatectl`
[sudo] password for orangepi: 
               Local time: Sun 2024-04-28 10:22:15 CST
           Universal time: Sun 2024-04-28 02:22:15 UTC
                 RTC time: Sun 2024-04-28 02:20:28
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

**如何设置时区？**
`sudo timedatectl set-timezone Asia/Shanghai`

确定时间没问题的基础之上，**再多执行几次复测吧**。这个命令目前在我这里是正常下载的。

**Comment by dudu502** [comment]
好的谢谢大佬

**Comment by dudu502** [comment]
大佬，能否出一期orangepi zero的openwrt视频
