### ISSUE TITLE
xiaoyakepper  容器启动不成功 

### ISSUE THREAD

**Issue by yuanxuguang** [wukongdaily/OrangePiShell#5]
1 Panel xiaoyakepper 日志显示 exec /bin/sh: exec format error

![image](https://github.com/wukongdaily/OrangePiShell/assets/33855042/fd118024-c3ff-450e-b538-d7a5f8900d49)

**Comment by wukongdaily** [comment]
这样看不出啥问题来。建议删除小雅keeper容器后，重新安装一次清理工具。执行如下代码

`bash -c "$(curl -sLk https://xiaoyahelper.ddsrem.com/aliyun_clear.sh | tail -n +2)" -s 5`

**Comment by yuanxuguang** [comment]
把 xiaoyakeeper 镜像容器卸载了。 然后执行了 
bash -c "$(curl -s https://xiaoyahelper.zengge99.eu.org/aliyun_clear.sh | tail -n +2)" -s 5
就可以了
