### ISSUE TITLE
xiaoya容器日志中报错，docker.xiaoya.pro服务不可用

### ISSUE THREAD

**Issue by goozi** [wukongdaily/OrangePiShell#6]
我使用的是orangepi zero 3  1G版本
在第6步时，xiaoya容器中日志显示如下：
启动容器(Bridge模式)......
INFO[2024-04-30 13:22:16] reading config file: data/config.json        
INFO[2024-04-30 13:22:16] load config from env with prefix:            
INFO[2024-04-30 13:22:16] init logrus...                               
INFO[2024-04-30 13:22:16] start server @ 127.0.0.1:5244                
INFO[2024-04-30 13:22:16] success load storage: [/©️ v.0428.1515(B)], driver: [UrlTree] 
Connecting to docker.xiaoya.pro (172.67.178.229:80)
wget: server returned error: HTTP/1.1 503 Service Unavailable
Failed to download version.txt file, the index file upgrade process has aborted
Connecting to docker.xiaoya.pro (172.67.178.229:80)
Connecting to gitlab.com (172.65.251.78:443)
saving to 'tvbox.zip'
tvbox.zip              7% |**                              |  108k  0:00:11 ETA
tvbox.zip             39% |************                    |  556k  0:00:03 ETA
tvbox.zip            100% |********************************| 1397k  0:00:00 ETA
'tvbox.zip' saved
Failed to download version.txt file, the index file upgrade process has aborted
httpd: bind: Address in use

请帮忙看一下问题出在哪里？感谢！！

**Comment by wukongdaily** [comment]
这可能是这几天小雅版本升级啦 和老版本也许不兼容数据库吧。
建议在1panel 删除xiaoya 这个容器。在镜像中也删除小雅这个镜像。
然后在脚本里从新安装小雅。
