### ISSUE TITLE
安装1panel面板管理工具失败

### ISSUE THREAD

**Issue by johnnyxowang** [wukongdaily/OrangePiShell#7]
![截屏2024-05-07 14 44 15](https://github.com/wukongdaily/OrangePiShell/assets/22126419/f344b36c-764b-4716-ada5-2c690faf491b)
安装1panel面板管理工具失败

**Comment by wukongdaily** [comment]
你的系统没有安装curl ，但是有wget
你可以先手动安装一次curl
如果是ubuntu或者debian系统的话
```
sudo apt update
sudo apt install curl
```

这段代码后续我会补充在选项 1 中。

**Comment by wukongdaily** [comment]
https://github.com/wukongdaily/OrangePiShell/commit/21fef713fb2648d8be1df458952e87795195785f

**Comment by johnnyxowang** [comment]
感谢
