### ISSUE TITLE
国外使用小雅的办法

### ISSUE THREAD

**Issue by henryxrl** [wukongdaily/OrangePiShell#9]
你好悟空，我已经成功的部署了全家桶（网上的教程以及你的教程），但是访问速度真的太慢了，且大多视频都打不开。请问如何在国外有效地使用小雅全家桶呢？只能翻墙回国吗？

**Comment by wukongdaily** [comment]
我是觉得全家桶的变量较多。因此我建议你先搭建一个基础版的小雅作为测试。昨天视频里顺便介绍了小雅TVBox。这个也蛮省心的。添加好阿里云盘账号和Pikpak账号，你可以尤其测测pikpak文件夹里的视频，比如 每日更新/pikpak 里的视频播放是否卡，如果不卡的话 说明就是阿里云盘服务器所在位置的问题，pikpak 这个网盘是海外的，服务器应该也在海外的。

**Comment by henryxrl** [comment]
多谢！我添加了 pikpak 之后果然大部分视频都能看了而且速度可接受（不仅是 pikpak 文件夹里的视频）。看来确实是阿里云盘服务器位置的问题。

不过还有一个问题想请教你。Apple TV 用 infuse 或 emby 连接小雅库之后，许多电视剧是没有的。比如，在小雅网页上可以选择“每日更新->电视剧->国产剧->庆余年->第二季”，而且播放没问题，但是在电视上是完全搜不到的。请问这是什么原因呢？有什么解决办法吗？

**Comment by wukongdaily** [comment]
Apple TV上我最近使用的软件是Fileball 它不用搜刮，或者说它没有海报墙，所以就不需要等搜刮过程了。庆余年2这个剧集貌似是在pikpak上的，确认填写过pikpak账号，还得尽量重启一次docker。infuse的话 是不是依赖于搜刮，确认是在有中过剧集的时候 再重新扫描一下媒体库。我感觉可能是docker 需要重启一次。哦对了。如果你用的是全家桶emby 。。。那其实海报墙跟实际的文件不是完全一致的，也就是说它扫描的时候有 不代表数据库里真的有。它有一个strm文件吧。它是根据这个出现海报的。总之你在重启docker试试吧

**Comment by henryxrl** [comment]
嗯嗯，我把所有小雅相关的容器都重启了，但好像问题依旧。你说得对，海报墙和实际文件不一致，emby 和 infuse 都这样。看来只能放弃漂亮的海报墙，用 Fileball 试试了。感谢！
